# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: KekikAkademi PyPI Yükleyici

on:
  push:
    branches:
      - "main"

jobs:
  PyPIYukleyici:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10.6"]

    steps:
      - name: Depo Kontrolü
        uses: actions/checkout@v2

      - name: Python ${{ matrix.python-version }} Sürümü Yükleniyor
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python Sürümünü Göster
        run: python -c "import sys; print(sys.version)"

      - name: Kütüphaneyi PyPI'ye Yükle
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python setup.py bdist_wheel sdist
          twine check dist/*
          python -m twine upload dist/*
          rm -rf build/
          rm -rf dist/
          rm -rf -- *.egg-info/